server:
  port: 8083

spring:
  data:
    mongodb:
      uri: mongodb+srv://leandro:ZYyyFGbXKrnJHNEo@cluster1.mlvzjvx.mongodb.net/microservicios?retryWrites=true&w=majority
      database: microservicios

  application:
    name: CALIFICACION-SERVICE

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
